config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    resource :relationship, only: [:create, :destroy]
  end

  resources :television_shows, only: [:create]

  root "homes#show"
end

app/models/guest.rb
class Guest
  def following?(_user)
    false
  end
end

app/models/recommended_item.rb
class RecommendedItem < ActiveRecord::Base
  belongs_to :television_show
  belongs_to :user

  delegate :title, to: :television_show, prefix: true
  delegate :username, to: :user

  def self.newest_first
    order(created_at: :desc)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/television_show.rb
class TelevisionShow < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true

  has_many :recommendations, as: :recommendable
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :username, presence: true, uniqueness: true

  has_many :recommended_items
  has_many :television_shows, through: :recommended_items
  has_many :following_relationships,
    class_name: "Relationship", foreign_key: :follower_id
  has_many :following, through: :following_relationships, source: :followed
  has_many :follower_relationships,
    class_name: "Relationship", foreign_key: :followed_id
  has_many :followers, through: :follower_relationships, foreign_key: :follower

  def users_to_follow
    self.class.where.not(id: self).first(3)
  end

  def recommend(television_show)
    unless television_shows.include?(television_show)
      television_shows << television_show
    end
  end

  def with_following
    [self] + following
  end

  def follow(user)
    following << user
  end

  def unfollow(user)
    following_relationships.find_by(followed: user).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  protect_from_forgery with: :exception

  def current_user
    super || Guest.new
  end

  private

  def signed_out?
    !signed_in?
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    if signed_out?
      render "pages/landing"
    else
      @recommended_items = RecommendedItem.
        where(user: current_user.with_following).
        newest_first

      render :show
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:user_id])

    current_user.follow(user)

    redirect_to user_path(user)
  end

  def destroy
    user = User.find(params[:user_id])

    current_user.unfollow(user)

    redirect_to user_path(user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(
      session_params,
      email_or_username: [:email, :username],
    )

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email_or_username, :password)
  end
end

app/controllers/television_shows_controller.rb
class TelevisionShowsController < ApplicationController
  def create
    television_show = TelevisionShow.find_or_create_by(television_show_params)

    unless current_user.recommend(television_show)
      flash[:error] = t(".cannot_recommend_twice")
    end

    redirect_to root_path
  end

  private

  def television_show_params
    params.require(:television_show).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @television_shows = @user.television_shows
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_header.html.erb
<header>
  <%= link_to title, root_path %>

  <ul class="header__items">
    <% if signed_in? %>
      <li class="header__item">
        <%= link_to t(".my_profile"), user_path(current_user) %>
      </li>
      <li class="header__item">
        <%= link_to t(".sign_out"), session_path, method: :delete %>
      </li>
    <% else %>
      <li class="header__item">
        <%= link_to t(".sign_in"), new_session_path %>
      </li>
    <% end %>
  </ul>
</header>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/homes/show.html.erb
<main>
  <h2>Recommendations</h2>
  <%= simple_form_for TelevisionShow.new do |form| %>
    <%= form.input :title, label: false %>
    <%= form.button :submit %>
  <% end %>

  <ul>
    <% @recommended_items.each do |recommended_item| %>
      <li>
        <strong>
          <%= recommended_item.television_show_title %>
        </strong>
        &mdash; <%= link_to recommended_item.username, recommended_item.user %>
      </li>
    <% end %>
  </ul>
</main>

<aside>
  <% if current_user.following.empty? %>
    <div>
      <p><%= t(".not_following_anyone") %></p>
      <ul>
        <% current_user.users_to_follow.each do |user| %>
          <li><%= link_to user.username, user %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
  <%= javascript_tag do %>
    var MOVIEDB_API_KEY = "<%= ENV.fetch("MOVIEDB_API_KEY") %>";
  <% end %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>

  <%= render "header" %>

  <div id="container">
    <%= yield %>
  </div>

  <%= render "javascript" %>
</body>
</html>

app/views/pages/landing.html.erb
<h1 class="logo">You should totally...</h1>

<ul>
  <li>...watch iZombie</li>
  <li>...read The Martian</li>
  <li>...learn Ruby</li>
</ul>

<a class="start-now" href="<%= new_user_path %>">
  <%= t(".start_now") %>
</a>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>

app/views/users/new.html.erb
<%= simple_form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.input :username %>
  </div>
  <div>
    <%= form.input :email %>
  </div>
  <div>
    <%= form.input :password %>
  </div>
  <div>
    <%= form.button :submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<section class="profile">
  <%= image_tag gravatar_image_url(@user.email, size: 200), class: "avatar" %>
  <p><%= @user.username %></p>
  <% if current_user.following?(@user) %>
    <%= button_to t(".unfollow"), user_relationship_path(@user), method: :delete %>
  <% else %>
    <%= button_to t(".follow"), user_relationship_path(@user) %>
  <% end %>
</section>

<section class="recommendations">
  <h2>I think you should totally check out</h2>

  <ul>
    <% @television_shows.each do |television_show| %>
      <li><%= television_show.title %></li>
    <% end %>
  </ul>
</section>